Support for Pandas Dataframe and Series
JacksonBurns/astartes pull request #127
Opened 2023-06-05 18:01 UTC by JacksonBurns

This PR is attempting to add support for Pandas Dataframes and Series directly.

Resolves #125

2023-06-05 21:49 UTC, JacksonBurns commented
Perhaps we could reduce the scope of this somewhat? Only support DataFrames for X and Series for y?

2023-06-05 23:56 UTC, kspieks commented
Firstly, `panda_handla` is a 10/10 choice for variable name 👌

As a first pass, I think it's okay to assume y is a Series object for now. However, my initial thought is that we would want to extend support to Dataframe as well. It's probably also a safe first pass assumption that even if y is a dataframe, it is only 1 column for now. I believe some splitting techniques basically perform KS or SPXY or extrapolation based on the target value and this would be easiest to implement if there is only one target value per entry.

I'll be pretty busy this week, but am happy to schedule a call sometime if it's helpful to discuss details about how to implement this feature.

2023-06-12 13:38 UTC, kspieks requested changes
Thanks for these updates! Except for one minor comment, things look great. We should be able to merge this today

2023-06-12 13:38 UTC, kspieks commented on astartes/utils/array_type_helpers.py
> +            X_train,
I believe this should be `X_test`? Not sure if this impacts the unittests

2023-06-12 13:40 UTC, kspieks commented on astartes/utils/array_type_helpers.py
> +            X_train,
Actually it looks like the unittests only test `train_X` but not `test_X`. Could we also test `test_X`?

2023-06-12 14:24 UTC, merged